version: '2'

services:
    mongo:
        build: ./
        image: mongo
        restart: always
        volumes:
            - './data/db:/data/db'
            - './data/log:/data/log'
        ports:
            - '27018:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123456
        command: --dbpath /data/db --logpath /data/log/dblog.log --auth
